#pragma once

#ifndef _SKILL_TYPE_H_
#define _SKILL_TYPE_H_

namespace model {
    enum SkillType {
        _SKILL_UNKNOWN_ = -1,
        SKILL_RANGE_BONUS_PASSIVE_1 = 0,
        SKILL_RANGE_BONUS_AURA_1 = 1,
        SKILL_RANGE_BONUS_PASSIVE_2 = 2,
        SKILL_RANGE_BONUS_AURA_2 = 3,
        SKILL_ADVANCED_MAGIC_MISSILE = 4,
        SKILL_MAGICAL_DAMAGE_BONUS_PASSIVE_1 = 5,
        SKILL_MAGICAL_DAMAGE_BONUS_AURA_1 = 6,
        SKILL_MAGICAL_DAMAGE_BONUS_PASSIVE_2 = 7,
        SKILL_MAGICAL_DAMAGE_BONUS_AURA_2 = 8,
        SKILL_FROST_BOLT = 9,
        SKILL_STAFF_DAMAGE_BONUS_PASSIVE_1 = 10,
        SKILL_STAFF_DAMAGE_BONUS_AURA_1 = 11,
        SKILL_STAFF_DAMAGE_BONUS_PASSIVE_2 = 12,
        SKILL_STAFF_DAMAGE_BONUS_AURA_2 = 13,
        SKILL_FIREBALL = 14,
        SKILL_MOVEMENT_BONUS_FACTOR_PASSIVE_1 = 15,
        SKILL_MOVEMENT_BONUS_FACTOR_AURA_1 = 16,
        SKILL_MOVEMENT_BONUS_FACTOR_PASSIVE_2 = 17,
        SKILL_MOVEMENT_BONUS_FACTOR_AURA_2 = 18,
        SKILL_HASTE = 19,
        SKILL_MAGICAL_DAMAGE_ABSORPTION_PASSIVE_1 = 20,
        SKILL_MAGICAL_DAMAGE_ABSORPTION_AURA_1 = 21,
        SKILL_MAGICAL_DAMAGE_ABSORPTION_PASSIVE_2 = 22,
        SKILL_MAGICAL_DAMAGE_ABSORPTION_AURA_2 = 23,
        SKILL_SHIELD = 24,
        _SKILL_COUNT_ = 25
    };
}

#endif
